### ISSUE TITLE
Images are excluded

### ISSUE THREAD

**Issue by FenixFeather** [FenixFeather/cs241-md2pdf#10]
Images are in the form ![description, possibly empty](url) and should be inserted properly into the latex form.

**Comment by FenixFeather** [comment]
External images to convert/remove/claim fair use:
- File System, Part 1 Introduction.tex:\includegraphics{http://upload.wikimedia.org/wikipedia/commons/a/a2/Ext2-inode.gif}
- File System, Part 8 Disk blocks example.tex:\includegraphics{http://uw714doc.sco.com/en/FS_admin/graphics/s5chain.gif}
- File System, Part 8 Disk blocks example.tex:(source: \url{http://uw714doc.sco.com/en/FS_admin/graphics/s5chain.gif})
- Pthreads, Part 1 Introduction.tex:\includegraphics{http://i.imgur.com/RPblpE1.png}

**Comment by FenixFeather** [comment]
\includegraphics{https://raw.githubusercontent.com/wiki/angrave/SystemProgramming/5DiningPhilosophers.png} should look like \includegraphics{tex_source/images/5DiningPhilosophers.png}

**Comment by bchong95** [comment]
Im thinking of having python http request all the image links 

import urllib
urllib.urlretrieve(src_url, filepath)
